# Generated by Django 2.1.5 on 2019-01-19 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='CK1',
        ),
        migrations.RemoveField(
            model_name='order',
            name='CK2',
        ),
    ]
